const { dir } = require("console");

module.exports = {
  // let Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  // Camphouse
  camphouse: [
    {
      type: "autogenerated",
      dirName: "camphouse",
    },
  ],
};
