const { dir } = require("console");

module.exports = {
  // let Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  // Camphouse
  camphouse: [
    {
      type: "autogenerated",
      dirName: "camphouse",
    },
  ],
  // vATC Suite
  vatcsuite: [
    {
      type: "autogenerated",
      dirName: "vatcsuite",
    },
  ],
  // JS Validator
  jsvalidator: [
    {
      type: "autogenerated",
      dirName: "js-validator",
    },
  ],
  // JS Logger
  jslogger: [
    {
      type: "autogenerated",
      dirName: "js-logger",
    },
  ],
};
